#define LAST_MANTISA_BIT_DECIMAL 95
#define LAST_MANTISA_BIT_BIGDECIMAL 223
#define ADDITIONAL_SIGN_1 96
#define ADDITIONAL_SIGN_2 97
#define ADDITIONAL_SIGN_BIG_1 224
#define ADDITIONAL_SIGN_BIG_2 225
#define SIGN_BIT_BIG 255

#include "../s21_decimal.h"
